//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarketingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public string product_Name { get; set; }
        public string product_image { get; set; }
        public Nullable<int> product_price { get; set; }
        public string product_description { get; set; }
        public Nullable<int> product_foreginKey_userTable { get; set; }
        public Nullable<int> product_foreginKey_categoryTable { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
