//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMarketingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_product = new HashSet<tbl_product>();
        }
    
        public int user_id { get; set; }
        public string user_Name { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_image { get; set; }
        public string user_contact { get; set; }
    
        public virtual ICollection<tbl_product> tbl_product { get; set; }
    }
}
